/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        base: '#0a0a0a',
        surface: '#0f0f0f',
        elevated: '#1a1a1a',
        'surface-hover': '#252525',
        'surface-active': '#2a2a2a',
        'input-bg': '#1a1a1a',
        'border-subtle': '#1a1a1a',
        'border-default': '#2a2a2a',
        'border-strong': '#3a3a3a',
        'border-focus': '#c9a961',
        'text-primary': '#ffffff',
        'text-secondary': '#a0a0a0',
        'text-muted': '#666666',
        'text-placeholder': '#4a4a4a',
        'text-inverse': '#000000',
        gold: {
          DEFAULT: '#c9a961',
          hover: '#d4b97a',
          muted: 'rgba(201, 169, 97, 0.15)',
          border: 'rgba(201, 169, 97, 0.3)',
        },
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#3b82f6',
        'cat-hair': '#a855f7',
        'cat-makeup': '#ec4899',
        'cat-sfx': '#ef4444',
        'cat-cast': '#fbbf24',
      },
      fontFamily: {
        ui: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        script: ['Courier Prime', 'Courier New', 'monospace'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
      transitionDuration: {
        fast: '100ms',
        normal: '150ms',
        slow: '300ms',
        slower: '500ms',
      },
    },
  },
  plugins: [],
};
